# Generated by Django 3.1.4 on 2020-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='Email',
            field=models.EmailField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='contatos',
            name='Name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
