# Generated by Django 3.1.4 on 2020-12-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20201213_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contatos',
        ),
    ]
